# Generated by Django 5.0.7 on 2024-10-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Texto do comentário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='MicroBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Texto do blog')),
            ],
            options={
                'verbose_name': 'Micro blog',
                'verbose_name_plural': "Micro blog's",
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome do usuario')),
                ('bio', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descrição do úsuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.microblog')),
                ('comentarios', models.ManyToManyField(blank=True, to='thoughts.comentario')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.usuario')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.AddField(
            model_name='microblog',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.usuario'),
        ),
        migrations.CreateModel(
            name='Curtir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.postagem')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.usuario'),
        ),
    ]
